# Generated by Django 5.0.7 on 2024-07-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('release_date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
